### ISSUE TITLE
Failed to compile code with 'use socket;'

### ISSUE THREAD

**Issue by little-arhat** [jdm/rust-socket#5]
Compiler fails when i'm trying to compile minimal example with socket lib.
https://gist.github.com/d60d84ca27fd48d34801 -- there are code and output.

I've successfully built minimal examples with other libraries, so it's not necessary 
compiler failure. 
Also, if i just "use socket;" and print some constants from library, all works well.

**Comment by jdm** [comment]
This is an error in rustc.

**Comment by jdm** [comment]
Follow along at https://github.com/mozilla/rust/issues/2170.

**Comment by little-arhat** [comment]
Thanks, i've tried to ask on #rust before reporting issue, but nobody couldn't tell me, is it compiler or library error.
